### ISSUE TITLE
Improve my elementary English in README

### ISSUE THREAD

**Issue by encX** [encX/cs-senior-finder#11]
I know, I know. Reading my current README.md, you might got a [cringe](https://www.urbandictionary.com/define.php?term=Cringe).

So any suggestion, rephrasing, change the vocab, anything would be really appreciated.

**Comment by Fayhen** [comment]
Hi! I can help you with this one. I'll submit a PR with a improved README in a short while.
I'll do my best to keep the language simple and concise.
